title: Alessandro Scicluna
logo: "/images/Alessandro-Scicluna.png?raw=true"
description: >
  Data science enthusiast with a passion for using data to solve real-world problems. Proven ability to apply supervised and unsupervised learning algorithms to large datasets to build and evaluate predictive models, as well as extract meaningful insights.
  <p style="margin-top: 0.5px">
  Seeking opportunities to collaborate with talented data scientists and continue learning in a fast-paced environment.
  <p>
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
google_analytics: G-4N3XBLKKP8
