title: Alessandro Scicluna
logo: "/images/Alessandro-Scicluna.png?raw=true"
description: >
  Here you can find some of my ML projects!
  <br><br>
  <a href="https://www.linkedin.com/in/alessandroscicluna/">LinkedIn</a> 
  
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
google_analytics: G-4N3XBLKKP8
